import { enemyDefinition, recipeSupplies, unitDefinition as unit } from '../core/catalog';
import { board, pile, shipment, stock, type AuthoredMission } from './authored';

/** The eight additions join Hollow, Siltwater, Woodland and Bramble in World 1. */
export const meadowAdditions: AuthoredMission[] = [
  {
    id: 'parts-and-paths', name: 'Parts and Paths', goal: 'Build Scout · reach the Garden flag',
    challenge: 'Carry a colored construction kit to a useful 3×3 building site.',
    brief: 'Hauler cannot finish this flag. Carry the yellow, green and charged battery to a building site, build Scout once, and send it through the garden. Save the blue pieces for the bonus.',
    grid: board([
      '~~~~~~~~~~~~~~~~~~', '~.....TT.........~', '~.....TT....::...~', '~..::........:...~',
      '~..::....TT......~', '~........TT......~', '~................~', '~....TT.....#....~',
      '~....TT.....#....~', '~................~', '~....:.......::..~', '~~~~~~~~~~~~~~~~~~',
    ]),
    rovers: [unit('hauler', 'carrier', { x: 3, y: 5 })],
    piles: [pile(4, 4, stock(0, 0, 1, 1, [100])), pile(4, 8, stock(0, 3))],
    goals: [{ id: 'garden', name: 'Garden', cell: { x: 14, y: 4 }, kinds: ['scout'] }],
    bonus: { kind: 'delivery', name: 'Garden repairs', description: 'Bring 3 blue pieces to the garden star.', cell: { x: 14, y: 9 }, ...shipment(0, 3) },
    enemies: [], blueprints: { scout: 1 }, seed: 4102,
  },
  {
    id: 'stone-gate', name: 'Stone Gate', goal: 'Open the gate · guide Snail to Orchard',
    challenge: 'Push a blocking rock from the correct side without sealing the exit.',
    brief: 'Dozer pushes away from its working position. Move the gate rock east, then go around it on the wide bank. The original Snail must reach Orchard; rebuilding another Snail will not rescue it.',
    grid: board([
      '~~~~~~~~~~~~~~~~~~', '~.......~........~', '~..TT...~...::...~', '~..TT...~...::...~',
      '~.......~........~', '~.......#........~', '~..::...~.....T..~', '~..::...~.....T..~',
      '~.......~........~', '~.......~..##....~', '~.......~........~', '~~~~~~~~~~~~~~~~~~',
    ]),
    rovers: [unit('dozer', 'dozer', { x: 3, y: 5 }), unit('snail', 'snail', { x: 3, y: 7 }), unit('hauler', 'carrier', { x: 3, y: 9 })],
    piles: [pile(4, 8, stock(3, 1))],
    goals: [{ id: 'orchard', name: 'Orchard', cell: { x: 14, y: 5 }, unitId: 'snail', kinds: ['snail'] }],
    bonus: { kind: 'delivery', name: 'Orchard tools', description: 'Bring 3 red and 1 blue to the upper-bank star.', cell: { x: 14, y: 2 }, ...shipment(3, 1) },
    enemies: [], blueprints: { dozer: 1 }, seed: 4104,
  },
  {
    id: 'split-kit', name: 'Split Kit', goal: 'Assemble Forklift · reach the Depot flag',
    challenge: 'Join a kit split across the river, then exploit the new carrier’s capacity.',
    brief: 'Hauler can carry four items. Bring the two yellow pieces and battery to the red/blue depot kit, then build Forklift in their 3×3 area. Its ten-item lift makes the twelve-green bonus delivery easier.',
    grid: board([
      '~~~~~~~~~~~~~~~~~~', '~.......~~.......~', '~..TT...~~..::...~', '~..TT...~~..::...~',
      '~.......~~.......~', '~....#..~~....T..~', '~....#..~~....T..~', '~.......==.......~',
      '~..::...~~.......~', '~..::...~~.......~', '~.......~~..##...~', '~.......~~.......~',
      '~.......~~.......~', '~~~~~~~~~~~~~~~~~~',
    ]),
    rovers: [unit('hauler', 'carrier', { x: 3, y: 6 })],
    piles: [pile(3, 4, stock(0, 0, 2, 0, [100])), pile(12, 3, stock(1, 1)), pile(13, 8, stock(0, 0, 0, 12))],
    goals: [{ id: 'depot', name: 'Depot', cell: { x: 15, y: 11 }, kinds: ['forklift'] }],
    bonus: { kind: 'delivery', name: 'Depot stock', description: 'Deliver 12 green to the northern depot star.', cell: { x: 15, y: 2 }, ...shipment(0, 0, 0, 12) },
    enemies: [], blueprints: { forklift: 1 }, seed: 4106,
  },
  {
    id: 'flat-battery', name: 'Flat Battery', goal: 'Restore the stranded Scout · reach Home',
    challenge: 'Deliver power to an original immobile unit and conserve a separate reserve.',
    brief: 'The stranded Scout has an empty installed battery. Haul a charged one to its 3×3 area, select Scout and replace the battery. Taking it apart loses the original rescue target. Keep the southern reserve for the bonus.',
    grid: board([
      '~~~~~~~~~~~~~~~~~~', '~....TT..........~', '~....TT...##.....~', '~.........##.....~',
      '~..::............~', '~..::..TTTT......~', '~......T.........~', '~......T....::...~',
      '~...........::...~', '~...TT...........~', '~...TT....T......~', '~.........T......~',
      '~................~', '~~~~~~~~~~~~~~~~~~',
    ]),
    rovers: [unit('hauler', 'carrier', { x: 3, y: 3 }), unit('scout', 'stranded', { x: 13, y: 9 }, 0)],
    piles: [pile(4, 3, stock(0, 0, 0, 0, [100])), pile(6, 10, stock(1, 0, 0, 1, [60]))],
    goals: [{ id: 'home', name: 'Home', cell: { x: 15, y: 3 }, unitId: 'stranded', kinds: ['scout'] }],
    bonus: { kind: 'delivery', name: 'Emergency reserve', description: 'Deliver 1 red, 1 green and a charged battery to the camp star.', cell: { x: 7, y: 2 }, ...shipment(1, 0, 0, 1, 1) },
    enemies: [], blueprints: { hauler: 1 }, seed: 4107,
  },
  {
    id: 'switchback-stations', name: 'Switchback Stations', goal: 'Build charging stops · reach Switchback',
    challenge: 'Plan charging stops through a long switchback and power the return journey.',
    brief: 'Hauler starts with only twenty charge. Build charging stations in the two side pockets beside their kits. Park beside a station to refill. The bonus sends you back carrying a reserve from the far end.',
    grid: board([
      '~~~~~~~~~~~~~~~~~~', '~................~', '~~~~~~~~~~~~~..~.~', '~................~',
      '~.~~~~~~~~~~~~~~~~', '~................~', '~~~~~~~~~~~~~..~.~', '~................~',
      '~.~~~~~~~~~~~~~~~~', '~................~', '~~~~~~~~~~~~~~~~.~', '~................~',
      '~~~~~~~~~~~~~~~~~~',
    ]),
    rovers: [unit('hauler', 'carrier', { x: 1, y: 1 }, 20)],
    piles: [pile(13, 2, recipeSupplies('pump')), pile(13, 6, recipeSupplies('pump')), pile(2, 10, stock(0, 0, 1, 1, [60]))],
    goals: [{ id: 'switchback', name: 'Switchback', cell: { x: 2, y: 11 }, unitId: 'carrier', kinds: ['hauler'] }],
    bonus: { kind: 'delivery', name: 'Reserve run', description: 'Return 1 yellow, 1 green and a charged battery to the start star.', cell: { x: 2, y: 1 }, ...shipment(0, 0, 1, 1, 1) },
    enemies: [], blueprints: { pump: 2 }, seed: 4108,
  },
  {
    id: 'forked-watch', name: 'Forked Watch', goal: 'Secure both crossings · reach Watch',
    challenge: 'Place finite static defenses at two separate choke points before a carrier passes.',
    brief: 'Only Sentry towers can fight here. Each tower attacks neighboring creatures automatically. Use the two separate kits to secure both crossings, then bring Hauler to Watch. Do not spend a tower plan at an unhelpful site.',
    grid: board([
      '~~~~~~~~~~~~~~~~~~', '~.......~~.......~', '~..TT...~~.......~', '~..TT...~~..::...~',
      '~.......~~..::...~', '~.......~~.......~', '~.......==.......~', '~..::...~~....T..~',
      '~..::...~~....T..~', '~.......~~.......~', '~.......==.......~', '~.......~~.......~',
      '~.......~~.......~', '~~~~~~~~~~~~~~~~~~',
    ]),
    rovers: [unit('hauler', 'carrier', { x: 3, y: 6 })],
    piles: [pile(7, 5, recipeSupplies('sentry', 100)), pile(14, 10, recipeSupplies('sentry', 100)), pile(4, 9, stock(0, 1, 0, 2, [60]))],
    goals: [{ id: 'watch', name: 'Watch', cell: { x: 15, y: 11 }, kinds: ['hauler'], clearEnemies: true }],
    bonus: { kind: 'delivery', name: 'Watch reserve', description: 'Bring 1 blue, 2 green and a charged battery to the Watch star.', cell: { x: 15, y: 2 }, ...shipment(0, 1, 0, 2, 1) },
    enemies: [enemyDefinition('bristleback', 'bridge-bristle', { x: 8, y: 6 }), enemyDefinition('crab', 'watch-crab', { x: 12, y: 10 })],
    blueprints: { sentry: 2 }, seed: 4110,
  },
  {
    id: 'orchard-convoy', name: 'Orchard Convoy', goal: 'Deliver 8 red · 4 blue · 4 yellow · 4 green',
    challenge: 'Coordinate tree relocation and repeated rock pushes before a heavy cargo delivery.',
    brief: 'Arborbot must lift the tree before Dozer can reach the rock. Push the rock along the narrow causeway until the wide bank lets you go around it. Bulk hauler can carry the twenty-piece shipment in one trip.',
    grid: board([
      '~~~~~~~~~~~~~~~~~~~~', '~~.......~~~......~~', '~........~~~.......~', '~..TT....~~~..::...~',
      '~..TT....~~~..::...~', '~........~~~.......~', '~........~~~.......~', '~........T#........~',
      '~........~~~.......~', '~..::....~~~..TT...~', '~..::....~~~..TT...~', '~........~~~.......~',
      '~........~~~.......~', '~~.......~~~......~~', '~~~......~~~.....~~~', '~~~~~~~~~~~~~~~~~~~~',
    ]),
    rovers: [unit('arborbot', 'arborbot', { x: 4, y: 5 }), unit('dozer', 'dozer', { x: 4, y: 6 }), unit('dumptruck', 'bulk', { x: 4, y: 9 })],
    piles: [pile(5, 9, stock(8, 4, 4, 4))],
    goals: [{ id: 'orchard-stock', name: 'Orchard stock', cell: { x: 17, y: 4 }, delivery: shipment(8, 4, 4, 4) }],
    bonus: { kind: 'arrival', name: 'Southern grove', description: 'Guide the original Arborbot to the southern grove star.', cell: { x: 17, y: 12 }, unitId: 'arborbot' },
    enemies: [], blueprints: { dumptruck: 1, arborbot: 1, dozer: 1 }, seed: 4111,
  },
  {
    id: 'meadow-siege', name: 'Meadow Siege', goal: 'Clear the far bank · guide Snail to Haven',
    challenge: 'Open a tree gate, make a causeway, fight as a team and escort a vulnerable survivor.',
    brief: 'Clear the tree at the river edge and borrow three spare land tiles for a crossing. Move the Wardens together onto the far bank before sending Snail. Bot workshop restores bots, not wheeled workers. All hostiles must be defeated before the original Snail reaches Haven.',
    grid: board([
      '~~~~~~~~~~~~~~~~~~~~', '~~.......~~~......~~', '~..TT....~~~.......~', '~..TT....~~~..::...~',
      '~........~~~..::...~', '~........~~~.......~', '~.......T~~~.......~', '~........~~~.......~',
      '~..::....~~~.......~', '~..::....~~~.......~', '~........~~~.......~', '~........~~~..TT...~',
      '~........~~~..TT...~', '~~.......~~~......~~', '~~~......~~~.....~~~', '~~~~~~~~~~~~~~~~~~~~',
    ]),
    rovers: [unit('warden', 'guard-a', { x: 4, y: 4 }), unit('warden', 'guard-b', { x: 4, y: 5 }), unit('workshop', 'workshop', { x: 3, y: 4 }), unit('scoop', 'scoop', { x: 3, y: 6 }), unit('arborbot', 'arborbot', { x: 3, y: 7 }), unit('snail', 'snail', { x: 3, y: 9 }), unit('hauler', 'carrier', { x: 4, y: 10 })],
    piles: [pile(6, 10, stock(0, 2, 0, 4, [100]))],
    goals: [{ id: 'haven', name: 'Haven', cell: { x: 17, y: 4 }, unitId: 'snail', kinds: ['snail'], clearEnemies: true }],
    bonus: { kind: 'delivery', name: 'Haven stores', description: 'Deliver 2 blue, 4 green and a charged battery to the southern star.', cell: { x: 17, y: 11 }, ...shipment(0, 2, 0, 4, 1) },
    enemies: [enemyDefinition('bristleback', 'north-bristle', { x: 14, y: 5 }), enemyDefinition('bristleback', 'south-bristle', { x: 14, y: 10 }), enemyDefinition('crab', 'haven-crab', { x: 17, y: 8 })],
    blueprints: { warden: 1, scoop: 1, arborbot: 1, hauler: 1 }, seed: 4112,
  },
];
