import { enemyDefinition, recipeSupplies, unitDefinition as unit } from '../core/catalog';
import { board, pile, manifest, stock, type AuthoredMission } from './authored';

/** Later Meadow puzzles build on the seven opening missions. */
export const meadowAdditions: AuthoredMission[] = [
  {
    id: 'switchback-stations', name: 'Switchback Stations', goal: 'Bring Hauler to Switchback',
    challenge: 'Place shared power at a fork, choose the coast or a Dozer shortcut, then charge a trapped Scout before opening its gate.',
    brief: 'Hauler starts with eight charge; Dozer and the grove Scout are empty. Build the camp Charging station east of its kit so it can reach Dozer as well as a visiting Hauler. Hauler can take the northern coast, or Dozer can push the shortcut rock east once and park clear of the opening. After Switchback, collect the second Charging station plan. The eastern kit can build a station inside the Scout enclosure using its diagonal 3×3 area. Charge Scout, move it down inside the grove, then push the gate rock east once with Dozer. Move Dozer clear and guide the original Scout to the camp star.',
    grid: board([
      '~~~~~~~~~~~~~~~~~~',
      '~~~~...........~~~',
      '~~~.......~~....~~',
      '~~...TT...~~.....~',
      '~....TT.~~~~.....~',
      '~.......~~~~.....~',
      '~~......#........~',
      '~~~....~.........~',
      '~~~~...~~~.......~',
      '~~~~~~~~~..TTT...~',
      '~~~~~~~~~..#..~..~',
      '~~~~~~~~~~~..~~~~~',
      '~~~~~~~~~~~~~~~~~~',
      '~~~~~~~~~~~~~~~~~~',
    ]),
    rovers: [unit('hauler', 'carrier', { x: 3, y: 6 }, 8), unit('dozer', 'gate-dozer', { x: 7, y: 6 }, 0), unit('scout', 'reserve-scout', { x: 12, y: 10 }, 0)],
    piles: [pile(5, 5, recipeSupplies('pump')), pile(14, 9, recipeSupplies('pump'))],
    goals: [{ id: 'switchback', name: 'Switchback', cell: { x: 15, y: 5 }, unitId: 'carrier', kinds: ['hauler'] }],
    bonus: { kind: 'arrival', name: 'Grove rescue', description: 'Guide the original grove Scout to the camp star.', cell: { x: 3, y: 7 }, unitId: 'reserve-scout' },
    enemies: [], blueprints: { pump: 1 }, seed: 4108,
    blueprintPickups: [{ blueprint: 'pump', cell: { x: 14, y: 5 }, afterMain: true }],
  },
  {
    id: 'forked-watch', name: 'Forked Watch', goal: 'Bring Hauler to Watch',
    challenge: 'Choose between defending two crossings and drawing their patrols away with a faster Scout; reserve or reclaim a kit for the water-only bonus.',
    brief: 'Bristleback patrols a circuit through both bridges; Crab circles the eastern landing. Scout can draw them away while Hauler takes the other crossing, or build the two Sentry towers to hold the choke points. Enemies notice a nearby unit before chasing it. After Watch, collect Duck’s plan. Use an unspent tower kit or reclaim a tower to build Duck and paddle to the quiet inlet.',
    grid: board([
      '~~~~~~~~~~~~~~~~~~',
      '~~~~~...~~.......~',
      '~~~TT...~~.......~',
      '~..TT...~~..::...~',
      '~.......~~..::...~',
      '~.......~~.~~....~',
      '~.......==.......~',
      '~..::...~~....T..~',
      '~..::...~~.~~.T..~',
      '~~~~~~~.~~.......~',
      '~.......==.......~',
      '~.......~~......~~',
      '~.......~~...~~~~~',
      '~~~~~~~~~~~~~~~~~~',
    ]),
    rovers: [unit('hauler', 'carrier', { x: 3, y: 6 }), unit('scout', 'bait', { x: 3, y: 10 })],
    piles: [pile(7, 5, recipeSupplies('sentry', 100)), pile(14, 10, recipeSupplies('sentry', 100))],
    goals: [{ id: 'watch', name: 'Watch', cell: { x: 15, y: 11 }, kinds: ['hauler'] }],
    bonus: { kind: 'arrival', name: 'Quiet inlet', description: 'Bring Duck to the quiet inlet.', cell: { x: 8, y: 1 }, kinds: ['duck'] },
    enemies: [
      { ...enemyDefinition('bristleback', 'bridge-bristle', { x: 8, y: 6 }), patrol: [{ x: 8, y: 6 }, { x: 13, y: 6 }, { x: 13, y: 9 }, { x: 7, y: 10 }, { x: 7, y: 6 }] },
      { ...enemyDefinition('crab', 'watch-crab', { x: 12, y: 10 }), patrol: [{ x: 12, y: 10 }, { x: 15, y: 10 }, { x: 13, y: 11 }, { x: 11, y: 10 }] },
    ],
    blueprints: { sentry: 2 }, seed: 4110,
    blueprintPickups: [{ blueprint: 'duck', cell: { x: 14, y: 11 }, afterMain: true }],
  },
  {
    id: 'orchard-convoy', name: 'Orchard Convoy', goal: 'Bring loaded Bulk hauler to Orchard',
    challenge: 'Coordinate tree relocation and repeated rock pushes before a heavy cargo cargo.',
    brief: 'Arborbot must lift the tree before Dozer can reach the rock. Push the rock along the narrow causeway until the wide bank lets you go around it. Bulk hauler can carry the twenty-piece manifest in one trip.',
    grid: board([
      '~~~~~~~~~~~~~~~~~~~~',
      '~~~~~~~~~~~~~~~~~~~~',
      '~~~..~~~~~~~~~~...~~',
      '~~.TT~~~~~~~~~~:...~',
      '~..TT~~~~~~~~~~:...~',
      '~........~~~~~~....~',
      '~........~~~..#....~',
      '~........T#...#....~',
      '~........~~~.......~',
      '~..::....~~~..TT...~',
      '~..::....~~~..TT~~~~',
      '~~~~~~~..~~~....~~~~',
      '~~~~.....~~~......~~',
      '~~~~~....~~~.....~~~',
      '~~~~~~~..~~~...~~~~~',
      '~~~~~~~~~~~~~~~~~~~~',
    ]),
    rovers: [unit('arborbot', 'arborbot', { x: 4, y: 5 }), unit('dozer', 'dozer', { x: 4, y: 6 }), unit('dumptruck', 'bulk', { x: 4, y: 9 })],
    piles: [pile(5, 9, stock(8, 4, 4, 4))],
    goals: [{ id: 'orchard-stock', name: 'Orchard', cell: { x: 17, y: 4 }, unitId: 'bulk', kinds: ['dumptruck'], cargo: manifest(8, 4, 4, 4) }],
    bonus: { kind: 'arrival', name: 'Southern grove', description: 'Bring an orchard tree to the southern grove with the original Arborbot.', cell: { x: 17, y: 12 }, unitId: 'arborbot', carryingTree: true },
    enemies: [], blueprints: {  }, seed: 4111,
  },
  {
    id: 'meadow-siege', name: 'Meadow Siege', goal: 'Clear the far bank · guide Snail to Haven',
    challenge: 'Open a tree gate, make a causeway, fight as a team and escort a vulnerable survivor.',
    brief: 'Clear the tree at the river edge and borrow three spare land tiles for a crossing. Move the Wardens together onto the far bank before sending Snail. Bot workshop restores bots, not wheeled workers. All hostiles must be defeated before the original Snail reaches Haven. After Haven, collect Frog’s plan and bring a green piece and the reserve battery to the far river shore. Build the amphibian beside the water to reach the river star.',
    grid: board([
      '~~~~~~~~~~~~~~~~~~~~',
      '~~~~~~~~.~~~~~~~~~~~',
      '~~~TT....~~~~.~~..~~',
      '~..TT....~~~..~~..~~',
      '~........~~~..::...~',
      '~........~~~..~~~..~',
      '~.......T~~~....#..~',
      '~........~~~....#..~',
      '~..::....~~~.#.....~',
      '~~.::....~~~.......~',
      '~~~......~~~~~.....~',
      '~........~~~~~TT...~',
      '~........~~~~~TT..~~',
      '~~~~~....~~~~~...~~~',
      '~~~~~~...~~~~~..~~~~',
      '~~~~~~~~~~~~~~~~~~~~',
    ]),
    rovers: [unit('warden', 'guard-a', { x: 4, y: 4 }), unit('warden', 'guard-b', { x: 4, y: 5 }), unit('workshop', 'workshop', { x: 3, y: 4 }), unit('scoop', 'scoop', { x: 3, y: 6 }), unit('arborbot', 'arborbot', { x: 3, y: 7 }), unit('snail', 'snail', { x: 3, y: 9 }), unit('hauler', 'carrier', { x: 4, y: 10 })],
    piles: [pile(6, 10, stock(0, 2, 0, 4, [100]))],
    goals: [{ id: 'haven', name: 'Haven', cell: { x: 17, y: 4 }, unitId: 'snail', kinds: ['snail'], clearEnemies: true }],
    bonus: { kind: 'arrival', name: 'River guest', description: 'Bring Frog to the river star.', cell: { x: 10, y: 11 }, kinds: ['frog'] },
    enemies: [enemyDefinition('bristleback', 'north-bristle', { x: 13, y: 5 }), enemyDefinition('bristleback', 'south-bristle', { x: 14, y: 10 }), enemyDefinition('crab', 'haven-crab', { x: 17, y: 8 })],
    blueprints: {  }, seed: 4112,
    blueprintPickups: [{ blueprint: 'frog', cell: { x: 16, y: 4 }, afterMain: true }],
  },
];
