import { enemyDefinition as enemy, recipeSupplies, unitDefinition as unit } from '../core/catalog';
import { board, pile, shipment, stock, type AuthoredMission } from './authored';

/** Shorelines and channels are individually authored; water depth matters to every route. */
export const seaMissions: AuthoredMission[] = [
  {
    id: 'tidepool-trail', name: 'Tidepool Trail', goal: 'Restore Frog · cross the shallows',
    challenge: 'Protect a shoreline battery transfer and rescue the original amphibian through a shallow route.',
    brief: 'Frog has an empty battery. Patrol boat must clear the Reef crab before Tugboat collects the shore battery and drops it beside Frog. Frog and Duck cross pale shallows but cannot use deep water. Restore the original Frog, then guide it to the eastern flag.',
    grid: board([
      'wwwwwwwwwwwwwwwwwwww', 'ww.......www......ww', 'w........www.......w', 'w...T....www.......w',
      'w...T....www..::...w', 'w........www..::...w', 'w..::....~~~.......w', 'w..::....~~~.......w',
      'w........~~~.......w', 'w........www.......w', 'w..sss...www.......w', 'w..sss...www...T...w',
      'w........www...T...w', 'ww.......www......ww', 'www......www.....www', 'wwwwwwwwwwwwwwwwwwww',
    ]),
    rovers: [unit('frog', 'frog', { x: 7, y: 7 }, 0), unit('duck', 'duck', { x: 16, y: 9 }), unit('tug', 'tug', { x: 10, y: 10 }), unit('patrolboat', 'patrol', { x: 10, y: 7 })],
    piles: [pile(8, 3, stock(0, 0, 0, 0, [100]))],
    goals: [{ id: 'frog-bank', name: 'Frog bank', cell: { x: 17, y: 4 }, unitId: 'frog', clearEnemies: true }],
    bonus: { kind: 'arrival', name: 'Duck nest', description: 'Guide the original Duck through the shallows to the western nest.', cell: { x: 4, y: 12 }, unitId: 'duck' },
    enemies: [enemy('water-crab', 'tide-crab', { x: 10, y: 2 })], blueprints: { frog: 1, duck: 1, tug: 1 }, seed: 4301,
  },
  {
    id: 'reef-courier', name: 'Reef Courier', goal: 'Launch Freighter at the eastern dock',
    challenge: 'Ferry a six-piece ship kit with a five-piece Tug hold, then sail the newly built ship through deep water.',
    brief: 'The Freighter kit is on the western shore. Tugboat can carry only five pieces, so it needs two shoreline deliveries to the eastern launch site. Its camp Marina provides power for the return. Build Freighter in deep water beside the new dock.',
    grid: board([
      'wwwwwwwwwwwwwwwwwwww', 'w......~wwwwww~....w', 'w......~wwwwww~....w', 'w..TT..~wwwwww~....w',
      'w..TT..~wwwwww~....w', 'w......~wwwwww~....w', 'w..::..~wwwwww~....w', 'w..::..~wwwwww~....w',
      'w......~wwwwww~....w', 'w......~wwwwww~....w', 'wwwwwwwwwwwwww~....w', 'wwwwwwwwwwwwww~....w',
      'wwwwwwwwwwwwww~....w', 'wwwwwwwwwwwwwwwwwwww', 'wwwwwwwwwwwwwwwwwwww', 'wwwwwwwwwwwwwwwwwwww',
    ]),
    rovers: [unit('tug', 'tug', { x: 8, y: 6 }), unit('marina', 'camp-marina', { x: 7, y: 6 })],
    piles: [pile(6, 7, recipeSupplies('freighter', 100)), pile(6, 9, stock(0, 0, 0, 6))],
    goals: [{ id: 'reef-port', name: 'Reef port', cell: { x: 12, y: 2 }, kinds: ['freighter'] }],
    bonus: { kind: 'delivery', name: 'Dock stores', description: 'Deliver 6 green from the western shore to the eastern star.', cell: { x: 15, y: 10 }, ...shipment(0, 0, 0, 6) },
    enemies: [], blueprints: { freighter: 1, tug: 1 }, seed: 4302,
  },
  {
    id: 'deepwater-maze', name: 'Deepwater Maze', goal: 'Excavate the canal · guide Fish to the Lagoon',
    challenge: 'Dig land barriers into connected water channels while disposing of each dirt load without sealing the fish route.',
    brief: 'Fish is trapped in the western pool. Scoop must dig three land plugs to join the pools. Each dig fills Scoop with dirt: use the southern waste ponds to unload between digs. The original Fish then swims through the canal to Lagoon. Tugboat ferries the waste-camp reserve for the bonus.',
    grid: board([
      '~~~~~~~~~~~~~~~~~~~~', '~..................~', '~..TT.....::.......~', '~..TT.....::.......~',
      '~..................~', '~..................~', '~.www.wwww.wwww.www~', '~.www.wwww.wwww.www~',
      '~.www.wwww.wwww.www~', '~..................~', '~..................~', '~.......~~~~.......~',
      '~.......~~~~.......~', '~.......~~~~.......~', '~..................~', '~~~~~~~~~~~~~~~~~~~~',
    ]),
    rovers: [unit('fish', 'fish', { x: 3, y: 7 }), unit('scoop', 'scoop', { x: 4, y: 4 }), unit('tug', 'tug', { x: 9, y: 12 }), unit('pump', 'station', { x: 6, y: 11 })],
    piles: [pile(7, 12, stock(0, 2, 0, 2, [60]))],
    goals: [{ id: 'lagoon', name: 'Lagoon', cell: { x: 17, y: 7 }, unitId: 'fish' }],
    bonus: { kind: 'delivery', name: 'Southern stores', description: 'Keep a water route to the southern star and deliver 2 blue, 2 green and a charged battery.', cell: { x: 12, y: 12 }, ...shipment(0, 2, 0, 2, 1) },
    enemies: [], blueprints: { scoop: 1, fish: 1 }, seed: 4303,
  },
  {
    id: 'marina-relay', name: 'Marina Relay', goal: 'Build remote boat power · restore Freighter',
    challenge: 'Bootstrap a forward charging berth with a kit larger than the courier hold and a limited starting battery.',
    brief: 'Tugboat begins partly drained. Carry the six-piece Marina kit in two loads to the shallow launch site. Build Marina beside the original empty Freighter; keep the kit on a different tile from the structure so the dock stays clear. The new berth also powers Tugboat for the bonus.',
    grid: board([
      'wwwwwwwwwwwwwwwwwwww', 'w......~wwwwww~....w', 'w......~wwwwww~....w', 'w..TT..~wwwwww~....w',
      'w..TT..~wwwwww~....w', 'w......~wwwwww~....w', 'w..::..~wwwwww~....w', 'w..::..~ww...w~....w',
      'w......~ww...w~....w', 'w......~wwwwww~....w', 'wwwwwwwwwwwwww~....w', 'wwwwwwwwwwwwww~....w',
      'wwwwwwwwwwwwww~....w', 'wwwwwwwwwwwwwwwwwwww', 'wwwwwwwwwwwwwwwwwwww', 'wwwwwwwwwwwwwwwwwwww',
    ]),
    rovers: [unit('tug', 'tug', { x: 8, y: 6 }, 45), unit('freighter', 'freighter', { x: 13, y: 6 }, 0)],
    piles: [pile(6, 6, recipeSupplies('marina')), pile(6, 9, stock(2, 0, 0, 5, [70]))],
    goals: [{ id: 'relay-port', name: 'Relay port', cell: { x: 12, y: 1 }, unitId: 'freighter' }],
    bonus: { kind: 'delivery', name: 'Relay reserve', description: 'Deliver 2 red, 5 green and a charged battery to the eastern star.', cell: { x: 15, y: 11 }, ...shipment(2, 0, 0, 5, 1) },
    enemies: [], blueprints: { marina: 1 }, seed: 4304,
  },
  {
    id: 'harbor-run', name: 'Harbor Run', goal: 'Secure shore and channel · deliver harbor stores',
    challenge: 'Coordinate naval protection and a separately built land defender before a real shoreline shipment.',
    brief: 'The sea predators and the land Gator threaten different routes. Build Warden from the eastern shore kit to clear Gator, while Patrol boat protects the shipping channel. Freighter delivers the camp stores to the outer shore after every threat is defeated. Enemy salvage supplies the bonus.',
    grid: board([
      '~~~~~~~~~~~~~~~~~~~~', '~~.....~~~wwwwww~~~~', '~......~~~wwwwww...~', '~......~~~wwwwww...~',
      '~......~~~wwwwww...~', '~.....:~~~wwwwww...~', '~.....:~~~wwwwww...~', '~.....:~~~wwwwww...~',
      '~......~~~wwwwww...~', '~......~~~wwwwww...~', '~~.....~~~wwwwww...~', '~~~...~~~~wwwwww...~',
      '~~~~~~~~~~wwwwww...~', '~~~~~~~~~~wwwwww...~', '~~~~~~~~~~wwwwww~~~~', '~~~~~~~~~~~~~~~~~~~~',
    ]),
    rovers: [unit('tug', 'tug', { x: 8, y: 6 }), unit('freighter', 'freighter', { x: 10, y: 7 }), unit('patrolboat', 'patrol', { x: 9, y: 8 }), unit('marina', 'marina', { x: 7, y: 6 })],
    piles: [pile(6, 7, stock(2, 4, 0, 6)), pile(17, 3, recipeSupplies('warden', 100))],
    goals: [{ id: 'harbor-stores', name: 'Harbor stores', cell: { x: 16, y: 9 }, delivery: shipment(2, 4, 0, 6), clearEnemies: true }],
    bonus: { kind: 'delivery', name: 'Channel reserve', description: 'Recover 5 blue and a charged battery for the western quay star.', cell: { x: 6, y: 9 }, ...shipment(0, 5, 0, 0, 1) },
    enemies: [enemy('water-crab', 'reef-crab', { x: 12, y: 3 }), enemy('shark', 'harbor-shark', { x: 12, y: 12 }), enemy('gator', 'harbor-gator', { x: 18, y: 8 })],
    blueprints: { warden: 1, tug: 1, patrolboat: 1, marina: 1 }, seed: 4305,
  },
  {
    id: 'wreck-recovery', name: 'Wreck Recovery', goal: 'Protect the wreck · restore the original ship',
    challenge: 'Recover a battery beyond a hostile reef and ferry it to an immobile ship without substituting a rebuilt copy.',
    brief: 'Freighter is powerless in the northern inlet. Patrol boat must recover power from Reef crab before facing Shark; Marina restores the patrol between encounters. Tugboat brings the recovered battery to the original ship. The southern salvage provides a second reserve for the bonus.',
    grid: board([
      'wwwwwwwwwwwwwwwwwwww', 'wwwwwwwwwww~~~~~~www', 'wwwwwwwwwww~....~www', 'wwwwwwwwwww~....~www',
      'wwwwwwwwwww~....~www', 'w......~www~....~www', 'w......~wwwwwwwwwwww', 'w......~wwwwwwwwwwww',
      'w..TT..~wwwwwwwwwwww', 'w..TT..~wwwwwwwwwwww', 'w......~wwwwwwwwwwww', 'w......~wwwwwwwwwwww',
      'w......~wwwwwwwwwwww', 'wwwwwwwwwwwwwwwwwwww', 'wwwwwwwwwwwwwwwwwwww', 'wwwwwwwwwwwwwwwwwwww',
    ]),
    rovers: [unit('freighter', 'wreck', { x: 16, y: 1 }, 0), unit('tug', 'tug', { x: 8, y: 7 }), unit('patrolboat', 'patrol', { x: 8, y: 8 }), unit('marina', 'marina', { x: 7, y: 8 })],
    piles: [], goals: [{ id: 'safe-berth', name: 'Safe berth', cell: { x: 8, y: 5 }, unitId: 'wreck', clearEnemies: true }],
    bonus: { kind: 'delivery', name: 'Recovery reserve', description: 'Recover 5 blue and a charged battery at the northern quay star.', cell: { x: 12, y: 3 }, ...shipment(0, 5, 0, 0, 1) },
    enemies: [enemy('water-crab', 'wreck-crab', { x: 10, y: 2 }), enemy('shark', 'wreck-shark', { x: 16, y: 12 })],
    blueprints: { freighter: 1, patrolboat: 1 }, seed: 4306,
  },
  {
    id: 'canal-foundry', name: 'Canal Foundry', goal: 'Excavate launch canals · build Patrol boat',
    challenge: 'Open land plugs to move a ship kit between isolated pools and build a combat ship beyond the barrier.',
    brief: 'Tugboat and the launch lagoon are in disconnected pools. Scoop opens the two land plugs and unloads dirt in the camp waste ponds. Ferry the Patrol boat kit to the eastern launch lagoon, then build it there to clear Reef crab. After the main, the patrol can donate its colored kit to build a Marina on the shallow launch berth, restoring Tugboat for the return delivery.',
    grid: board([
      '~~~~~~~~~~~~~~~~~~~~', '~..................~', '~..TT.........::...~', '~..TT.........::...~',
      '~..................~', '~..................~', '~.wwww.wwww.ww~wwww~', '~.wwww.wwww.ww~wwww~',
      '~.wwww.wwww.wwwwwww~', '~..................~', '~..................~', '~..~~~.............~',
      '~..~~~.............~', '~..~~~.............~', '~..................~', '~~~~~~~~~~~~~~~~~~~~',
    ]),
    rovers: [unit('tug', 'tug', { x: 3, y: 7 }), unit('scoop', 'scoop', { x: 5, y: 4 }), unit('pump', 'station', { x: 7, y: 10 })],
    piles: [pile(2, 5, recipeSupplies('patrolboat', 100)), pile(2, 9, stock(2, 0, 0, 4))],
    goals: [{ id: 'foundry-patrol', name: 'Launch patrol', cell: { x: 17, y: 7 }, kinds: ['patrolboat'], clearEnemies: true }],
    bonus: { kind: 'delivery', name: 'Launch reserve', description: 'Deliver 2 red and 4 green from camp to the eastern shore star.', cell: { x: 18, y: 9 }, ...shipment(2, 0, 0, 4) },
    enemies: [enemy('water-crab', 'foundry-crab', { x: 18, y: 8 })], blueprints: { patrolboat: 1, marina: 1 }, seed: 4307,
  },
  {
    id: 'gator-backwater', name: 'Gator Backwater', goal: 'Defend the banks · open Fish’s escape',
    challenge: 'Use shallow-water pursuit to lure amphibious threats into shore defenses before excavating a vulnerable rescue passage.',
    brief: 'Build the two shore towers before sending Frog to draw the Gators toward them. Fish stays safe in its enclosed pool until Scoop removes the land plug. Clear both Gators, open the passage and guide the original Fish to the eastern lagoon. Use short retreats so the Gators keep chasing. The first recovered battery can restore Frog before the second lure; keep its old charged battery at the shoreline for the reserve.',
    grid: board([
      '~~~~~~~~~~~~~~~~~~~~', '~..................~', '~..TT..............~', '~..TT..............~',
      '~.www..............~', '~.www..............~', '~.www.~~~~~~~~~~~~.~', '~......~~~~~~~~~~~.~',
      '~......~~~~~~~~~~~.~', '~......~~~~~~~~~~~.~', '~......~~~~~~~~~~~.~', '~......~~~~~~~~~~~.~',
      '~..::..~~~~~~~~~~~.~', '~..::..~~~~~~~~~~~.~', '~......~~~~~~~~~~~.~', '~~~~~~~~~~~~~~~~~~~~',
    ]),
    rovers: [unit('frog', 'bait', { x: 5, y: 10 }), unit('fish', 'fish', { x: 3, y: 5 }), unit('scoop', 'scoop', { x: 4, y: 8 }), unit('tug', 'tug', { x: 7, y: 12 }), unit('pump', 'station', { x: 4, y: 11 })],
    piles: [pile(5, 9, recipeSupplies('sentry', 100)), pile(5, 10, recipeSupplies('sentry', 100))],
    goals: [{ id: 'fish-escape', name: 'Fish escape', cell: { x: 16, y: 6 }, unitId: 'fish', clearEnemies: true }],
    bonus: { kind: 'delivery', name: 'Backwater reserve', description: 'Deliver 8 green and two remaining charged batteries to the eastern shore star.', cell: { x: 18, y: 12 }, ...shipment(0, 0, 0, 8, 2) },
    enemies: [enemy('gator', 'gator-a', { x: 13, y: 8 }), enemy('gator', 'gator-b', { x: 15, y: 12 })], blueprints: { sentry: 2 }, seed: 4308,
  },
  {
    id: 'island-handoffs', name: 'Island Handoffs', goal: 'Ship the reserve · haul it inland',
    challenge: 'A shipment larger than Freighter’s hold needs repeated sea transfers and a newly built inland carrier.',
    brief: 'Thirty green pieces must reach an inland flag that ships cannot approach. Build a far-shore Forklift from its separate colored kit. Freighter makes two sea deliveries, and Forklift makes three inland runs. Each shore has the charging berth needed to keep this long supply chain moving.',
    grid: board([
      'wwwwwwwwwwwwwwwwwwwwwwwww', 'w......~wwwwww~.........w', 'w......~wwwwww~.........w', 'w..TT..~wwwwww~.........w',
      'w..TT..~wwwwww~.........w', 'w......~wwwwww~.........w', 'w..::..~wwwwww~.........w', 'w..::..~wwwwww~.........w',
      'w......~wwwwww~.........w', 'w......~wwwwww~.........w', 'w......~wwwwww~.........w', 'w......~wwwwww~.........w',
      'w......~wwwwww~.........w', 'wwwwwwwwwwwwww~.........w', 'wwwwwwwwwwwwww~.........w', 'wwwwwwwwwwwwwwwwwwwwwwwww',
    ]),
    rovers: [unit('freighter', 'ship', { x: 8, y: 6 }), unit('marina', 'west-marina', { x: 7, y: 6 }), unit('marina', 'east-marina', { x: 14, y: 6 }), unit('pump', 'east-station', { x: 16, y: 6 })],
    piles: [pile(6, 8, stock(0, 0, 0, 30)), pile(6, 5, recipeSupplies('forklift', 100)), pile(6, 10, stock(3, 2, 0, 0, [80]))],
    goals: [{ id: 'inland-reserve', name: 'Inland reserve', cell: { x: 20, y: 3 }, delivery: shipment(0, 0, 0, 30) }],
    bonus: { kind: 'delivery', name: 'Homeward reserve', description: 'Return 3 red, 2 blue and a charged battery to the inland star.', cell: { x: 20, y: 12 }, ...shipment(3, 2, 0, 0, 1) },
    enemies: [], blueprints: { forklift: 1 }, seed: 4309,
  },
  {
    id: 'storm-line', name: 'Storm Line', goal: 'Restore the fleet · clear both channels',
    challenge: 'Two separated patrols share limited repair berths while distinct water-depth routes isolate their encounters.',
    brief: 'The two Patrol boats begin with partial charge in separate channels. Build a Marina at each shallow berth before battle. The northern channel has two Reef crabs; the southern channel has two Sharks, so restore that patrol between encounters. Tugboat collects salvage from both channels for the bonus.',
    grid: board([
      'wwwwwwwwwwwwwwwwwwww', 'w.....~wwwwww~.....w', 'w.....~wwwwww~.....w', 'w.....~wwwwww~.....w',
      'w.....~wwwwww~.....w', 'w.....~wwwwww~.....w', 'w.....~wwwwww~.....w', 'w..................w',
      'w..................w', 'w.....~wwwwww~.....w', 'w.....~wwwwww~.....w', 'w.....~wwwwww~.....w',
      'w.....~wwwwww~.....w', 'w.....~wwwwww~.....w', 'w.....~wwwwww~.....w', 'wwwwwwwwwwwwwwwwwwww',
    ]),
    rovers: [unit('patrolboat', 'north', { x: 7, y: 3 }, 35), unit('patrolboat', 'south', { x: 7, y: 11 }, 45), unit('tug', 'tug', { x: 8, y: 4 })],
    piles: [pile(5, 3, recipeSupplies('marina')), pile(5, 11, recipeSupplies('marina'))],
    goals: [{ id: 'storm-berth', name: 'Storm berth', cell: { x: 12, y: 13 }, unitId: 'south', clearEnemies: true }],
    bonus: { kind: 'delivery', name: 'Storm reserve', description: 'Deliver 12 blue and two charged batteries from the separate channels to the western quay star.', cell: { x: 5, y: 6 }, ...shipment(0, 12, 0, 0, 2) },
    enemies: [enemy('water-crab', 'north-a', { x: 12, y: 2 }), enemy('water-crab', 'north-b', { x: 12, y: 5 }), enemy('shark', 'south-a', { x: 10, y: 12 }), enemy('shark', 'south-b', { x: 12, y: 14 })],
    blueprints: { marina: 2 }, seed: 4310,
  },
  {
    id: 'last-reserves', name: 'Last Reserves', goal: 'Turn the last battery into a fleet rescue',
    challenge: 'A sole charged battery must first fund combat salvage, then restore an original immobile ship.',
    brief: 'Only one loose starting battery has charge. Tugboat carries it to the empty Patrol boat. Defeat Reef crab first and replace the patrol’s battery with its salvage before facing Shark. That second recovered battery powers the original Freighter. Keep the remaining reserve for the bonus.',
    grid: board([
      'wwwwwwwwwwwwwwwwwwww', 'wwwwwwwwwwwwww~....w', 'ww....~~wwwwww~....w', 'w..TT..~wwwwww~....w',
      'w..TT..~wwwwww~....w', 'w......~wwwwww~....w', 'w..::..~wwwwww~....w', 'w..::..~wwwwww~....w',
      'w......~wwwwww~....w', 'w......~wwwwww~....w', 'wwwwwwwwwwwwww~....w', 'wwwwwwwwwwwwww~....w',
      'wwwwwwwwwwwwww~....w', 'wwwwwwwwwwwwwwwwwwww', 'wwwwwwwwwwwwwwwwwwww', 'wwwwwwwwwwwwwwwwwwww',
    ]),
    rovers: [unit('patrolboat', 'patrol', { x: 9, y: 8 }, 0), unit('freighter', 'freighter', { x: 0, y: 10 }, 0), unit('tug', 'tug', { x: 8, y: 7 }, 55)],
    piles: [pile(6, 7, stock(0, 0, 0, 0, [50])), pile(6, 9, stock(2, 0, 0, 2))],
    goals: [{ id: 'reserve-port', name: 'Reserve port', cell: { x: 12, y: 2 }, unitId: 'freighter', clearEnemies: true }],
    bonus: { kind: 'delivery', name: 'Final reserve', description: 'Deliver 2 red, 2 green and one remaining charged battery to the eastern star.', cell: { x: 15, y: 12 }, ...shipment(2, 0, 0, 2, 1) },
    enemies: [enemy('water-crab', 'reserve-crab', { x: 12, y: 2 }), enemy('shark', 'reserve-shark', { x: 12, y: 12 })], blueprints: { patrolboat: 1, freighter: 1 }, seed: 4311,
  },
  {
    id: 'three-tides', name: 'Three Tides', goal: 'Open the coast · secure the fleet · deliver the island reserve',
    challenge: 'Combine tree and rock work, forward land construction, staged naval combat and a shipment too large for one ship.',
    brief: 'The final reserve is split between camp and enemy salvage. Lift the dock tree, push the boulder north twice, then dig the two cleared dock tiles into water. Unload that dirt in the two gaps in the southern causeway. Patrol boats protect the shipping channel while Warden secures the far shore. Ship a Forklift kit first, then combine the colored reserves and two recovered batteries at the inland flag.',
    grid: board([
      'wwwwwwwwwwwwwwwwwwwwwwww', 'w.........~wwwwww~.....w', 'w.........~wwwwww~.....w', 'w...TT....~wwwwww~.....w',
      'w...TT....~wwwwww~.....w', 'w.........~wwwwww~.....w', 'w....::....wwwwww~.....w', 'w....::...Twwwwww~.....w',
      'w.........#wwwwww~.....w', 'w..........wwwwww~.....w', 'w.........~wwwwww~.....w', 'w.........~wwwwww~.....w',
      'w.........~wwwwww~.....w', 'w.........~wwwwww~.....w', 'w.........~wwwwww~.....w', 'w.........~wwwwww~.....w',
      'w.........===~~==......w', 'w.........~~~~~~~......w', 'wwwwwwwwwwwwwwwwwwwwwwww', 'wwwwwwwwwwwwwwwwwwwwwwww',
    ]),
    rovers: [unit('arborbot', 'arborbot', { x: 6, y: 7 }), unit('dozer', 'dozer', { x: 7, y: 8 }), unit('scoop', 'scoop', { x: 7, y: 10 }), unit('forklift', 'camp-carrier', { x: 5, y: 10 }), unit('freighter', 'ship', { x: 12, y: 9 }), unit('patrolboat', 'patrol-a', { x: 12, y: 5 }), unit('patrolboat', 'patrol-b', { x: 12, y: 12 }), unit('marina', 'west-marina', { x: 10, y: 11 }), unit('marina', 'east-marina', { x: 17, y: 11 }), unit('pump', 'east-station', { x: 20, y: 10 })],
    piles: [pile(9, 7, recipeSupplies('forklift', 100)), pile(9, 8, stock(6, 6, 6, 2)), pile(21, 3, recipeSupplies('warden', 100))],
    goals: [{ id: 'three-tides-reserve', name: 'Island reserve', cell: { x: 22, y: 3 }, delivery: shipment(6, 6, 6, 6, 2), clearEnemies: true }],
    bonus: { kind: 'arrival', name: 'Last grove', description: 'Guide the original Arborbot to the far-island grove through the southern shallows.', cell: { x: 21, y: 16 }, unitId: 'arborbot' },
    enemies: [enemy('water-crab', 'final-crab', { x: 15, y: 2 }), enemy('shark', 'final-shark-a', { x: 15, y: 6 }), enemy('shark', 'final-shark-b', { x: 15, y: 15 }), enemy('gator', 'final-gator', { x: 21, y: 9 })],
    blueprints: { forklift: 1, warden: 1, marina: 1, patrolboat: 1 }, seed: 4312,
  },
];
